---
title: "Zebrafish CAGE shifting analysis"
author: "Gabe Zentner"
date: "1/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(TSRexploreR)
library(filesstrings)
library(tidyverse)
library(GenomicRanges)
library(readxl)
library(plyranges)
library(rtracklayer)
library(org.Dr.eg.db)
library(clusterProfiler)
library(ReactomePA)
```

### Data preparation
```{r}
# Generate sample sheet
samples <- data.frame(sample_name = before_last_dot(before_last_dot(list.files("bigwigs", pattern = "plus"))), 
                      file_1 = list.files("bigwigs", full.names = TRUE, pattern = "plus"), 
                      file_2 = list.files("bigwigs", full.names = TRUE, pattern = "minus"),
                      condition = before_last_dot(before_last_dot(list.files("bigwigs", pattern = "plus"))))

# Read in annotation
annotation <- file.path("danRer7.refGene.gtf")

# Create TSRexploreR object
exp <- tsr_explorer(sample_sheet = samples, genome_annotation = annotation)

# Import TSS bigWigs
exp <- tss_import(exp)

# Change negative-strand TSS negative scores to positive
corrected_scores <- map(exp@experiment$TSSs, function(x) {
  as.data.frame(x) %>%
    mutate(score = ifelse(strand == "-", score * -1, score)) %>%
    makeGRangesFromDataFrame(keep.extra.columns = TRUE)
})

exp@experiment$TSSs <- corrected_scores

# Format TSSs
exp <- format_counts(exp, data_type = "tss")
```

### Threshold exploration
```{r fig.align = "center"}

# Annotate TSSs relative to known genomic features
exp <- annotate_features(exp, data_type = "tss", feature_type = "transcript", 
                         upstream = 500, downstream = 500, )

# Perform threshold analysis
threshold_data <- explore_thresholds(exp, steps = 1, max_threshold = 20, 
                                     samples = c(
                                       "unfertilized.egg", "fertilized.egg", "64cells", 
                                       "512cells", "high", "oblong", "sphere.dome", "30p.dome",
                                       "shield", "somites", "prim6", "prim6.rep1",
                                       "prim6.rep2", "prim20"), 
                                     use_normalized = FALSE)

# Plot threshold analysis
plot_threshold_exploration(threshold_data, ncol = 4, point_size = 1) +
  scale_color_viridis_c() +
  xlim(0,20)
```
### TSR detection
```{r}
exp <- tss_clustering(exp, threshold = 5, max_distance = 25, max_width = 250)
```

### Shifting analysis
```{r}
# Remove unfertilized egg from the list of samples to loop over in order to prevent self-comparison
the_shift_list <- filter(exp@meta_data$sample_sheet, sample_name != "unfertilized.egg") %>%
  dplyr::select(sample_name) %>%
  as_tibble

# Perform pairwise shift analyses
for(sample in the_shift_list$sample_name) {
  exp <- tss_shift(exp, 
                   sample_1 = c(TSS = "unfertilized.egg", TSR = "unfertilized.egg"),
                   sample_2 = c(TSS = sample, TSR = sample),
                   max_distance = 100, min_threshold = 10, n_resamples = 1000L,
                   comparison_name = str_c("unfertilized.egg.vs.", sample))
}
```

### Shift number plot
```{r fig.align = "center"}
map(exp@shifting$results, function(x) {
  x %>% 
  mutate(shift_status = case_when(
    shift_score < 0 ~ "upstream",
    shift_score > 0 ~ "downstream",
    TRUE ~ "unshifted"
  )) %>%
    group_by(shift_status) %>%
    count
}) %>% 
  as_tibble %>% 
  pivot_longer(everything(), names_to = "sample", values_to = "n") %>%
  mutate(sample = fct_relevel(sample, 
                              "unfertilized.egg.vs.fertilized.egg", "unfertilized.egg.vs.64cells", 
                              "unfertilized.egg.vs.512cells", "unfertilized.egg.vs.high", 
                              "unfertilized.egg.vs.oblong", "unfertilized.egg.vs.sphere.dome", 
                              "unfertilized.egg.vs.30p.dome", "unfertilized.egg.vs.shield", 
                              "unfertilized.egg.vs.somites", "unfertilized.egg.vs.prim6",
                              "unfertilized.egg.vs.prim6.rep1", "unfertilized.egg.vs.prim6.rep2",
                              "unfertilized.egg.vs.prim20")) %>%
  ggplot(aes(x = sample, fill = n$shift_status, y = n$n)) +
  geom_col(position = "stack") +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  scale_y_continuous(expand = c(0,0), limits = c(0,1550)) +
  scale_fill_viridis_d(end = 0.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### Shift score rank plots
```{r fig.align = "center"}
plot_shift_rank(exp) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  scale_fill_viridis_c()
```

### Distribution of shifted TSRs
```{r fig.align = "center"}
exp <- annotate_features(exp, data_type = "shift", feature_type = "transcript", 
                         upstream = 500, downstream = 500)

distribution <- genomic_distribution(exp, data_type = "shift")

plot_genomic_distribution(distribution) +
  scale_fill_viridis_d(direction = -1)
```

### Gene tracks
```{r fig.align = "center"}
gene_tracks(exp, feature_name = "cenpe", promoter_only = TRUE, 
            samples = c(TSS = "unfertilized.egg", TSS ="prim20"),
            use_normalized = FALSE, axis_scale = 1, upstream = 100,
            tss_colors = viridis::viridis(4)
            )

gene_tracks(exp, feature_name = "rpl35", promoter_only = TRUE, 
            samples = c(TSS = "unfertilized.egg", TSS ="prim20"),
            use_normalized = FALSE, axis_scale = 1, upstream = 100,
            tss_colors = viridis::viridis(4)
            )

gene_tracks(exp, feature_name = "zbtb22b", promoter_only = TRUE, 
            samples = c(TSS = "unfertilized.egg", TSS ="prim20"),
            use_normalized = FALSE, axis_scale = 1, upstream = 100,
            tss_colors = viridis::viridis(4)
            )


```
